// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// ------------------ //
// quadrature_encoder //
// ------------------ //

#define quadrature_encoder_wrap_target 0
#define quadrature_encoder_wrap 14
#define quadrature_encoder_pio_version 1

static __pio_const uint16_t quadrature_encoder_program_instructions[] = {
            //     .wrap_target
    0x20a0, //  0: wait   1 pin, 0
    0x3f20, //  1: wait   0 pin, 0               [31]
    0xad42, //  2: nop                           [13]
    0xa0c3, //  3: mov    isr, null
    0x4001, //  4: in     pins, 1
    0xa026, //  5: mov    x, isr
    0x0040, //  6: jmp    x--, 0
    0x00cc, //  7: jmp    pin, 12
    0xa04a, //  8: mov    y, ~y
    0x008a, //  9: jmp    y--, 10
    0xa04a, // 10: mov    y, ~y
    0x000d, // 11: jmp    13
    0x008d, // 12: jmp    y--, 13
    0xa0c2, // 13: mov    isr, y
    0x8000, // 14: push   noblock
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program quadrature_encoder_program = {
    .instructions = quadrature_encoder_program_instructions,
    .length = 15,
    .origin = -1,
    .pio_version = quadrature_encoder_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config quadrature_encoder_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + quadrature_encoder_wrap_target, offset + quadrature_encoder_wrap);
    return c;
}
#endif

