"""CSV + branded PDF export and session logging for CLOUDS Spectral Engine.

Hardware-free: takes a calibration + a full detector frame and writes the
analysis-ready, common-grid spectrum (measurement, reference, transmission,
absorbance) plus a one-page branded PDF report.
"""
from __future__ import annotations

import csv
import os
from datetime import datetime

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.image as mpimg
from matplotlib.figure import Figure

from . import processing as P

NAVY = "#01386a"
_HERE = os.path.dirname(os.path.abspath(__file__))
_ASSETS = os.path.normpath(os.path.join(_HERE, os.pardir, "assets"))


def timestamp() -> str:
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def _common(cal, frame):
    """Resample onto a shared nm grid -> (grid, meas, ref, T, A). On a single-channel
    instrument (no reference channel) ref/T/A come back as NaN."""
    m = cal.by_role("measurement")
    r = cal.by_role_optional("reference")
    mc = m.slice(frame).astype(float)
    if r is None:
        grid = np.asarray(m.wavelengths, dtype=float)
        nan = np.full(grid.shape, np.nan)
        return grid, mc, nan, nan, nan
    rc = r.slice(frame).astype(float)
    grid = P.common_grid(m.wavelengths, r.wavelengths, 256)
    mi = P.resample(m.wavelengths, mc, grid)
    ri = P.resample(r.wavelengths, rc, grid)
    return grid, mi, ri, P.transmission(mi, ri), P.absorbance(mi, ri)


def _fmt(v, prec):
    return "" if not np.isfinite(v) else f"{v:.{prec}f}"


def write_spectrum_csv(path, cal, frame, meta: dict) -> str:
    grid, mi, ri, trans, absb = _common(cal, frame)
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["# CLOUDS Spectral Engine - spectrum export"])
        for k, v in meta.items():
            w.writerow([f"# {k}", v])
        w.writerow(["# calibration", cal.source])
        w.writerow(["wavelength_nm", "measurement", "reference", "transmission", "absorbance"])
        for i in range(len(grid)):
            w.writerow([f"{grid[i]:.3f}", _fmt(mi[i], 1), _fmt(ri[i], 1),
                        _fmt(trans[i], 5), _fmt(absb[i], 5)])
    return path


def write_pdf_report(path, cal, frame, meta: dict) -> str:
    grid, mi, ri, trans, absb = _common(cal, frame)
    m = cal.by_role("measurement")
    r = cal.by_role_optional("reference")
    fig = Figure(figsize=(8.27, 11.69), dpi=150)
    fig.patch.set_facecolor("white")

    head = fig.add_axes([0.06, 0.90, 0.66, 0.08]); head.axis("off")
    head.text(0, 0.62, "CLOUDS Spectral Engine", color=NAVY, fontsize=20,
              fontweight="bold", va="center")
    head.text(0, 0.08, "Dual-spectrometer report  -  BEXUS 38", color="#5a6b7a",
              fontsize=11, va="center")
    logo = os.path.join(_ASSETS, "clouds_logo.png")
    if os.path.exists(logo):
        axl = fig.add_axes([0.74, 0.905, 0.20, 0.07]); axl.axis("off")
        axl.imshow(mpimg.imread(logo))

    meta_ax = fig.add_axes([0.06, 0.74, 0.88, 0.14]); meta_ax.axis("off")
    lines = [f"{k}: {v}" for k, v in meta.items()]
    lines.append(f"detector: {cal.instrument.get('detector')}   pixels: {cal.n_pixels}")
    lines.append(f"calibration: {cal.source[:92]}")
    meta_ax.text(0, 1.0, "\n".join(lines), color="#33414d", fontsize=9,
                 va="top", family="monospace")

    ax1 = fig.add_axes([0.10, 0.42, 0.84, 0.26])
    ax1.plot(m.wavelengths, m.slice(frame), color=NAVY, lw=1.0, label="measurement  Ch1")
    if r is not None:
        ax1.plot(r.wavelengths, r.slice(frame), color="#4d8fd1", lw=1.0, label="reference  Ch2")
    ax1.set_ylabel("counts (16-bit)"); ax1.set_xlabel("wavelength (nm)")
    ax1.grid(alpha=0.15); ax1.legend(fontsize=7)
    ax1.set_title("Spectrum (counts)", color=NAVY, fontsize=12)
    for sp in ax1.spines.values():
        sp.set_color("#d3dde6")

    ax2 = fig.add_axes([0.10, 0.09, 0.84, 0.24])
    if r is not None:
        ax2.plot(grid, trans, color="#1D9E75", lw=1.2)
        ax2.set_ylabel("transmission  meas / ref"); ax2.set_xlabel("wavelength (nm)")
        ax2.set_ylim(bottom=0)
        ax2.set_title("Transmission (measurement / reference)", color=NAVY, fontsize=12)
    else:
        ax2.axis("off")
        ax2.text(0.5, 0.5, "single-channel instrument - no reference channel\n"
                 "(transmission / absorbance not available)", color="#8a97a3",
                 fontsize=11, ha="center", va="center")
    ax2.grid(alpha=0.15)
    for sp in ax2.spines.values():
        sp.set_color("#d3dde6")

    fig.text(0.06, 0.045, "generated by CLOUDS Spectral Engine", color="#8a97a3", fontsize=8)
    fig.savefig(path)
    return path


class SessionLogger:
    """Append one summary row per acquisition to a session CSV."""

    def __init__(self, path):
        self.path = path
        self._f = open(path, "w", newline="", encoding="utf-8")
        self._w = csv.writer(self._f)
        self._w.writerow(["iso_time", "exposure_ms", "navg", "meas_peak",
                          "meas_peak_nm", "ref_peak", "ref_peak_nm", "sat_frac"])
        self._n = 0

    def log(self, cal, frame, exposure_ms, navg, sat_frac):
        m = cal.by_role("measurement")
        r = cal.by_role_optional("reference")
        mc = m.slice(frame)
        mi = P.robust_peak_index(mc)                 # glitch-robust, matches the live readout
        if r is not None:
            rc = r.slice(frame)
            ri = P.robust_peak_index(rc)
            ref_peak, ref_nm = int(rc[ri]), f"{float(r.wavelengths[ri]):.2f}"
        else:
            ref_peak, ref_nm = "", ""                # single channel: no reference
        self._w.writerow([datetime.now().isoformat(timespec="milliseconds"),
                          f"{exposure_ms:g}", navg,
                          int(mc[mi]), f"{float(m.wavelengths[mi]):.2f}",
                          ref_peak, ref_nm, f"{sat_frac:.4f}"])
        self._f.flush()
        self._n += 1

    @property
    def count(self) -> int:
        return self._n

    def close(self):
        try:
            self._f.close()
        except Exception:
            pass
